### ISSUE TITLE
using the Egypt remaster

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#1]
@virtushda, would you be interested in doing a [pull request](https://github.com/ZetaGlest/zetaglest-source/blob/develop/CONTRIBUTING.md) to merge your [remaster of the Egypt faction](https://github.com/virtushda/EgyptRemaster)?

**Comment by virtushda** [comment]
Couldn't you just take the mod and add it to your repo? I'm not planning on updating it any further, and if I do, you'll know about it.

**Comment by andy5995** [comment]
>Couldn't you just take the mod and add it to your repo? I'm not planning on updating it any further, and if I do, you'll know about it.

Done. Please do let us know if you update in the future. Thank you!
