### ISSUE TITLE
updating textures and models for the Autumn tileset

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#110]
A while back, @virtushda and some other folks pointed out the graphics are not very modern. While @KeithSammut has been been updating many models for the factions, I started thinking it would be nice if tilesets could be improved, too. As far as I know, there hasn't been any major update to the Autumn tileset in years.

https://github.com/ZetaGlest/zetaglest-data/tree/develop/tilesets/autumn

No one person would have to update an entire tileset, or commit to that, but if he or she wanted to take on only parts of one, that would be cool, too.

**Comment by KeithSammut** [comment]
For the autumn tilset, I have in mind to make butterflies fly around some rocks, include tree leaf swaying and a moving  lizard on one of the models. I can change the statues if necessary.

**Comment by andy5995** [comment]
Interesting. Since other tilesets will need updating too, I'd suggest using the lizard on the desert tileset instead.

**Comment by KeithSammut** [comment]
oh, will do, but my mistake, I confused autumn with spring, I could place butterflies in the spring tileset

**Comment by andy5995** [comment]
We can discuss the details in #tilesets in the Discord chat room, to cut back on emails going to repo watchers.
