### ISSUE TITLE
[scenario] add Witch's Hunt

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#15]
@onpon4 Could you make a pull request to add this to the repo?

Instructions for doing pull requests are at https://github.com/ZetaGlest/zetaglest-source/blob/develop/CONTRIBUTING.md#pull-requests

Just replace "zetaglest-source" with "zetaglest-data"

If you need support along the way, you are welcome to join our [Discord server](https://discord.gg/WaAaXS7) or [IRC channel](http://webchat.freenode.net/?channels=%23zetaglest-dev&uio=d4).

We'll create separate tickets for each scenario you'd like to add.

**Comment by andy5995** [comment]
@onpon4 Please remember to add your name (or username) and personal link to https://github.com/ZetaGlest/zetaglest-source/blob/develop/AUTHORS.md

**Comment by onpon4** [comment]
I've opened a pull request for it, and I've done the same for the others as well.

**Comment by andy5995** [comment]
Thank you, and I've received notifications for all 4. I should be able to merge them by the end of the day. :)

**Comment by andy5995** [comment]
completed by cdbe837b73937ac36442873663f3f8b3355b44c2
