### ISSUE TITLE
new music for the menu

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#21]
This is the current music that plays at the main menu

https://github.com/ZetaGlest/zetaglest-data/blob/develop/data/core/menu/music/menu_music.ogg

I don't have anything in mind, but if any creative types would like to send some samples, please do so.

If we decide on one, you can do a [pull request](https://github.com/ZetaGlest/zetaglest-source/blob/develop/CONTRIBUTING.md#pull-requests) and add yourself to the [AUTHORS](https://github.com/ZetaGlest/zetaglest-source/blob/develop/AUTHORS.md) file.

Any potential contributors are also welcome to join us on [Discord](https://discord.gg/WaAaXS7)

Music should be in ogg format and match the specs of the original menu_music.ogg file.

Please mention the license you'd like to release it under. To select a license, one suggestion is the [Creative Commons license chooser](https://creativecommons.org/choose/)

You can attach samples to this ticket (you'll have to zip them first). Or, if you prefer, you can submit your sample directly to a pull request. That way, even if they are not approved, GitHub will record a record of your work. If you do submit them with a PR, replace the current menu_music.ogg file in the same location, and do not zip it.

**Comment by Masterfireheart** [comment]
aha, something on github I can finally contribute to!

I'll definitely take a stab at this later tonight. I'm assuming you're intending on keeping the orchestral theme (although I can do a lot more than that as well), are you looking for something a little more melodic or something more ambient?

(license would definitely be CC BY-SA 4.0)

**Comment by andy5995** [comment]
Yes, an orchestral theme would be good. I think melodic would be better than ambient for this type of game. Though I bet ambient could work.. I guess I'd need to hear a sample to make that decision. So let's focus on melodic.

Thanks @Masterfireheart !

**Comment by andy5995** [comment]
How's this coming along, @Masterfireheart ?

**Comment by Masterfireheart** [comment]
heya, sorry about the wait, caught the flu over the past week

I whipped up a theme draft in 30 minutes which you can hear here https://clyp.it/552siyl2, gonna continue working on it tomorrow afternoon and see if I can get some good layering in :)

**Comment by andy5995** [comment]
Hey, that's great.. and I'm glad you are recovering from the flu okay!

That clip sounds like you went from major to minor.. but it didn't get *too* dark...

To my ears, the clip is fitting for the game. I'll pass it around the Discord chat room and get some more feedback.

**Comment by andy5995** [comment]
The feedback I received from the team is that it sounds too random for the game and not exciting enough.

"The music needs to set the environment up for an epic battle. It needs to be energetic, strong, and should serve as an emotional build up to the in-game competitive excitement (ie. it should leverage user expectation)."

**Comment by andy5995** [comment]
@KeithSammut has a pull request open for this. Just waiting for review by @Jammyjamjamman and final approval.

**Comment by andy5995** [comment]
This was completed by @KeithSammut in https://github.com/ZetaGlest/zetaglest-data/commit/74c3df6d17c09afc88024b9c4476e125cc3cee5b. Thank you!
