### ISSUE TITLE
[submission][The Wild Hunt] New scenario needs feedback and testing

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#23]
Please try this new scenario by @KeithSammut and provide feedback

https://github.com/KeithSammut/wild_hunt

>In this scenario you require patience and resilisnce, as it is very hard to dominate over all animals, and the other animals in the game are split in teams, so a mix of animals can team against each other or yourself .

>You must consume grass at first, but once you evolve to a predator, you can only consume other animals.

To try it, just clone or unzip the repo into your scenarios directory.

Also, please remember to "star" the scenario repo!

Thank you...

**Comment by andy5995** [comment]
Wild Hunt:

Download Link:

https://github.com/KeithSammut/wild_hunt

Scenario Validation:

https://gist.github.com/KeithSammut/b16e5fc7641bf157e57f1491b138d37d

**Comment by andy5995** [comment]
Thank you @KeithSammut . It'll take me a few days before I can review this again.

**Comment by andy5995** [comment]
This problem still exists

https://github.com/KeithSammut/wild_hunt/issues/1

**Comment by KeithSammut** [comment]
what does that mean? you dont even upgrade to a duck?

**Comment by andy5995** [comment]
Right.

**Comment by andy5995** [comment]
The problem is due to this bug in the ZG source code, and depends on the OS/compiler. (works for @KeithSammut  on windows, but not me, on Debian 9)

https://github.com/ZetaGlest/zetaglest-source/issues/73

**Comment by andy5995** [comment]
This scenario has been added to the Game Mods, accessible from the ZetaGlest main menu.

Please leave feedback on the maintainer's GitHub repo at https://github.com/KeithSammut/wild_hunt/
