### ISSUE TITLE
radius value for shaman should be set to 5

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#232]
radius value for shaman should be set to 5 under the "stop" and the "move" skill.

https://github.com/ZetaGlest/zetaglest-data/blob/549912032a80e3dd7164cafc818f0c1852e58563/techs/zetapack/factions/indian/units/shaman/shaman.xml#L65

Please remember to "star" this project.

**Comment by ludoro** [comment]
On it.
