### ISSUE TITLE
remove extra animals from the map

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#26]
This makes a big change how food is supplied.. hopefully for the better. I wanted to hear some discussion before proceeding though.

Please see my comments on #25 

I think if this goes forward, would be good to enable a farm upgrade, so less farms have to be built over time.

**Comment by KeithSammut** [comment]
and food would be hunted instead! That was my idea after this scenario

**Comment by andy5995** [comment]
@KeithSammut In my PR, I just have the farm producing extra food, and no ability to produce chickens.

https://github.com/ZetaGlest/zetaglest-data/pull/25/files

Though I would be open to the idea of hunting animals. To my knowledge, this can't be done yet. "Harvesting" units is not possible without change the source code of the game itself (which could be done).

I haven't had time yet to play your scenario. Right now, Is there a way to harvest animals for food?

**Comment by KeithSammut** [comment]
ah alright :P

**Comment by andy5995** [comment]
I opened a ticket to implement harvesting units (ZetaGlest/zetaglest-source#35)

**Comment by andy5995** [comment]
As seen on the ticket pings above, animals for food was removed so far from only Norse and  Romans (romans now use the "grace" provided by the Elves). So far, the only negative feedback has come from vibe, a frequent, regular player.

There haven't been final decisions yet on whether food from animals will be removed from the other factions.

**Comment by andy5995** [comment]
After some feedback and testing, cows were given back to Norse.

It seems removing the animals is still a somewhat controversial issue.

@Jammyjamjamman believes that the cows and pigs don't contribute much to lag (https://github.com/ZetaGlest/zetaglest-source/issues/142) because they aren't given many move commands.

As for getting resources from animals by killing them, I don't see that anyone would like that feature unless this were implemented first https://github.com/ZetaGlest/zetaglest-source/issues/178

**Comment by andy5995** [comment]
After some changes, some factions produce "invisible units" from the farm. After more testing is done, we'll make the changes consistent across all factions. I anticipate that would happen after the first or second release, depending on how much the game is played and how much feedback we get.
