### ISSUE TITLE
[romans] enhancing or redesigning the graphics

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#28]
Is anyone interested in enhancing or redesigning the graphics for the [roman faction](https://github.com/ZetaGlest/zetaglest-data/tree/develop/techs/zetapack/factions/romans/units)?

**Comment by andy5995** [comment]
The dir for the units and models:

https://github.com/ZetaGlest/zetaglest-data/tree/develop/techs/zetapack/factions/romans/units

**Comment by andy5995** [comment]
@KeithSammut , are you still working on the temple and the Colosseum? I don't think there will be any problem replacing the main forum with a Colosseum.

**Comment by KeithSammut** [comment]
oh sorry for the late response, I'll start working on it, I have been very
busy lately

**Comment by andy5995** [comment]
I'll close this and we'll make tickets for any individual models that need updating. @KeithSammut made new models for the temple and forum (now a Colosseum)
