### ISSUE TITLE
Mod Centre does not delete original 7z file after extraction

### ISSUE THREAD

**Issue by mathusummut** [ZetaGlest/zetaglest-data#31]
This is a small bug and it has always been there since the mod centre was introduced.

**Comment by andy5995** [comment]
I never thought of this as a bug. If one of us makes a mod and hosts a game, the only way it will transfer is if the 7z file is present.

**Comment by mathusummut** [comment]
Oh ok, then leave it no problem. :)

**Comment by Jammyjamjamman** [comment]
I think it can package the mod before transfer, but it will only do this if the .7z is missing, so it saves computing every time someone downloads your mod (but at the expense of extra disk space usage).

Definitely debatable whether it should work like this and whether there should be an option to save 7z's or not.

**Comment by andy5995** [comment]
>I think it can package the mod before transfer, but it will only do this if the .7z is missing,

Any time I've hosted, if I didn't have a 7z file present, clients would never receive my mod. Never. So if there's a way to package the mod, it's in the configuration and needs to be documented somewhere.

**What's needed is documentation added to the web site.**

It should answer these questions

Where did the 7z files come from?
Is it safe to delete them? (Yes you can, but then clients can't download them if you host a custom server unless they are available in the mod center)

**Comment by andy5995** [comment]
ticket created https://github.com/ZetaGlest/zetaglest.github.io/issues/68
