### ISSUE TITLE
[submission]Atlantis Scenario

### ISSUE THREAD

**Issue by KeithSammut** [ZetaGlest/zetaglest-data#39]
**Atlantis:**

A Scenario about the pursue of the great underwater city of Atlantis. You must build a raft and face various challenges in order to obtain the map to the gateway to Atlantis.

**Download Link:**

[https://github.com/KeithSammut/atlantis](https://github.com/KeithSammut/atlantis)

**Scenario Validation:**

[https://gist.github.com/KeithSammut/9e9d12bd5d43e565221b78970d598872](https://gist.github.com/KeithSammut/9e9d12bd5d43e565221b78970d598872)

**Comment by andy5995** [comment]
Thank you @KeithSammut .

I played Atlantis for a while, but didn't win. It was interesting and fun. :)

I need to review it more though so I can leave some useful feedback. I should be able to get to that within the next few days.

**Comment by andy5995** [comment]
This has been added to the mod center. Thank you!
