### ISSUE TITLE
Error = 1281 [invalid value] for text

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#4]
Using the new Egypt data (#1), this message repeats in the console.

[/home/andy/src/ZetaGlest/zetaglest-source/source/shared_lib/sources/graphics/gl/font_textFTGL.cpp::Render] Line 246 Error = 1281 [invalid value] for text [Game duration 00:03:54 Local: 10:06]

No problems in-game though.

**Comment by mathusummut** [comment]
This is now fixed, I forgot in which commit, but I fixed this.
