### ISSUE TITLE
models for trojan horse needed

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#46]
The trojan horse doesn't have the ability to move yet, but we will be adding that to the xml file.

https://github.com/ZetaGlest/zetaglest-data/blob/eb6c22ce44d290b8860dbc1451eb79c0b12f2b25/techs/zetapack/factions/greece/units/trojan_horse/trojan_horse.xml#L48-L118

The model used right now when it's not moving should be changed. (https://github.com/ZetaGlest/zetaglest-data/tree/develop/techs/zetapack/factions/greece/units/trojan_horse/models)

I think it's using a default statue model from a tileset (https://github.com/ZetaGlest/zetaglest-data/tree/develop/tilesets/birch_forest/models)

Also, an additional model will be needed for movement. Some models in this game have "people" attached to them, such as the battering ram:

https://github.com/ZetaGlest/zetaglest-data/tree/develop/techs/zetapack/factions/greece/units/battering_ram/models

So the best situation is a model of a trojan horse that appears to be pulled by other units.

I'd guess that would be a lot more time-consuming for artists though, and at a minimum I'm thinking something like a wooden horse standing on a flatbed, with wheels underneath, would suffice.

[some pictures](https://en.wikipedia.org/wiki/Trojan_Horse)

**Comment by KeithSammut** [comment]
Oh? I didn't see this Sorry

**Comment by andy5995** [comment]
Completed by @KeithSammut in https://github.com/ZetaGlest/zetaglest-data/commit/5fb74067563737d4686f46d2eed017031d323131
