### ISSUE TITLE
Keep an eye on user acquisition: Magitech-only by default

### ISSUE THREAD

**Issue by biels** [ZetaGlest/zetaglest-data#48]
I think adding a bunch of factions to the default pack is NOT the way to go.
For example, when I first openend age of empires on a friend's computer I found myself having to chhose a faction without knowing what any faction does and assuming that I would definitely not end up knowing how every faction works. The same happens with another open source game called widelands for example.
Sure, for experienced players this adds variety and more content, but it adds a lot of friction for more users to get into the community.
The time it takes a player to know the game is at best linear with the amount of content in the game
So I would say that we have to be careful and handle it properly.
My proposition would be to keep the Magitech techtree and make it the default. Maybe we don't even neeed to download the whole zetapack into new isntallations. If a user desires it can download it form the mod center. Maybe in an "official" section though.

**Comment by mathusummut** [comment]
For the cool scenarios to be playable, I think at least Egypt, Indian, Magic and Tech should be pre-installed. Maybe even Norsemen and Persians. You do offer a good point however, maybe the other factions can be added as an optional `zetapack-extended`.

**Comment by andy5995** [comment]
I started with computers when some games were 10k in size, and software was distributed on 360K floppy disks. I still prefer to keep things minimal.

But I also see how things are today. Most RTS games are pretty big, and download speeds are light-years ahead of when I started. But I still think about people who don't have blazing-fast Internet speeds.

I haven't made up my mind yet, and will want some feedback from @Jammyjamjamman as well.

At this moment, I don't think that having a second download that contains most of the factions as a viable option.

New players who only have 2 factions wouldn't be able to play with players who have all the factions.

If players who  have all the factions wanted to play with new players, they would be forced to only have 2 factions to play with.

Maintenance costs would be increased. Not only would we have be supplying a tech tree, but also scenarios and translations. One tutorial is for the Indian faction. That would need changing. How would translations be handled?

>For example, when I first openend age of empires on a friend's computer I found myself having to chhose a faction without knowing what any faction does and assuming that I would definitely not end up knowing how every faction works. The same happens with another open source game called widelands for example.

I usually suggest to new users they pick one faction and learn it before trying another. When I tried 0 A.D., I understood that learning 1 faction at a time was the best way to improve my understanding of the game. I think most people will realize that if they try to play 5 different factions at a time, they're going to have a difficult time learning how to play better.

A doc specifically for new users could also emphasize suggestions for beginners. Whether or not new users will read it, or accept advice about learning 1 faction at a time is their choice.

>My proposition would be to keep the Magitech techtree and make it the default

I don't see that Magic is one of the best factions for new players. But here again, I'd want more feedback.

And I think we need more feedback from new players before we make decisions on what to change.  A system that encourages players to leave feedback is something to consider. My email is listed on the repo, the GitHub ticket system is available, as well as the Discord server and in-game chat. Perhaps we need to add more reminders in the docs to leave feedback, or someone may want to create a Google Form that users could use to submit anonymous feedback.

When I've read through the MG forum, much of the feedback is for feature requests.  I don't know if I've seen any users on the forum or in IRC that are bothered by the amount of factions. If that's a problem for new users, then they have to tell us.

I think the best way to retain users is to implement some of those feature requests, and definitely listen to what players are saying, and not dismiss them outright.

But you are leaving feedback, so I do want to consider it. :) While I don't see separating the zetapack, using faction links to have a "default" tech tree with only 2 factions is a much stronger possibility.

Splitting up the zetapack maybe a better option in the future, when we have more contributors and maintenance becomes easier. Right now we are missing essential docs, we don't have any docs that show how to write scenarios or tech trees, and no strategy guides, something which new users look for.

I'll keep the discussion open. It's definitely worth considering.

**Comment by andy5995** [comment]
It's not live yet, but I started some docs for new users:

https://zetaglest.github.io/docs/tips_for_beginners.html

**Comment by biels** [comment]
I think it is a matter of not overwhelming new users. From here, the more
features and content the game has, the better. But it should be
progressive. The game starts with 2 factions and very few scenarios and
tilesets. Also the tutorial should be in tech (it is simpler than magic and
more intuitive). For the scenarios those that were in the original glest
would do.
From here, the player can download everything from the mod center. It would
be a great that the mod center is accessible from a game lobby, and you can
choose to download the current tech tree if you don't have it and it is on
the mod center.
Think about popular games. They have a low entry barrier for new users.
My main concern wasn't initial bundle size, it was more about user
experience. But that would be an improvement in that aspect as well.

Really, take a step back and take a look at this, because it is an easy way
to improve the game and its community that we as developers often overlook.

**Comment by Jammyjamjamman** [comment]
I think my opinion may differ a lot from others, but I'll share the idea ;-).

Based purely on graphics, the factions I would choose to be default are:
* Tech
* Magic
* Elves
* Egypt
* Romans (zeta version)
* Japanese
* Natulka

This would require some significant re-balancing.

I do understand where @biels is coming from. I used to find DOTA 2 very daunting with choices (the fact that MOBA players are d***heads doesn't help ;-) (J/k *some* MOBA lovers)). I found out later that it's a MUCH better idea to stick to one character than to try them all. The trouble is when you a few characters in a game/ a few factions in ZG, (in my experience) you can learn any other in one game.

One option would be to start with only 2 factions, then provide zetapack as an optional **booster** pack, or something along that line...

**Comment by andy5995** [comment]
Related discussion at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/zetaglest/bLyEMBlmWTo

**Comment by MirceaKitsune** [comment]
I've already expressed an opinion that all techs with low quality assets should either get new art, either be removed. Sadly this includes most MG factions, which have varying degrees of problematic assets... MagiTech is the only one which has only assets of flawless quality in my book.

**Comment by andy5995** [comment]
@biels , I'll reply to your comments in #138 here

>The game should be progressive, starting with magic and tech and then when the player already knows the game (mechanics, resources, armor types, unit levels, upgrades, teams, commands, ...) then the user gets to a point where he may want to start trying new factions and techtrees.

Yes, this should be added to the documentation.

>We have to get into the skin of a player that just discovered ZetaGlest and that has never played any similar game.

I've learned over time and with much psychotherapy that by trying to guess or assume how people think or feel doesn't work. At some point a general survey would be more effective.

>But the matter is to not give players too much choices and information at once.

To me, this sounds like it contradicts some core open source software principles. We can suggest things in the documentation and give people information and choices, and allow them to make informed decisions.

We'll continue to try to compromise and things will evolve over time, and changes will be made as we get more feedback over time.

@mathusummut @Jammyjamjamman I think this ticket can be closed. At this time, I don't see that we'll only be offering Magitech as the default. I think user acquisition will best be done by continuing to work on bugs, feature improvements, and documentation.

**Comment by biels** [comment]
Okay, I understand.

> To me, this sounds like it contradicts some core open source software principles. We can suggest things in the documentation and give people information and choices, and allow them to make informed decisions.

I don't totally agree with that, since I think that OSS should not be any different than commercial software. Wouldn't it be cool to have an UX similar to common commercial games?

But yes, I think that for now we're fine with having a classic / simple preset and then the whole zetapack available. We will need better balancing though.
