### ISSUE TITLE
Mobile British units should have a regen value of 1

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#51]
Mobile [British units](https://github.com/ZetaGlest/zetaglest-data/tree/develop/techs/zetapack/factions/british/units) should have a regen value of 1

An example of how to do this is at 

https://github.com/ZetaGlest/zetaglest-data/blob/254b3dd645faba8d5c29011b494e7297a23015c7/techs/zetapack/factions/indian/units/worker/worker.xml#L10

**Comment by MintRamney** [comment]
I can change this tonight!
