### ISSUE TITLE
change uniform-select value on workers and main buildings

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#54]
This must be done to all the factions, but only involves 2 units per faction.

`<uniform-selection value="true"/>`

That needs to be changed to "false" on workers and main building to prevent the bug mentioned in  https://github.com/ZetaGlest/zetaglest-source/issues/74

**Comment by mathusummut** [comment]
Is this fixed for all factions?

**Comment by KeithSammut** [comment]
currently yes I believe
