### ISSUE TITLE
Greece:psiloi (slinger) too strong?

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#55]
@KeithSammut suggested that the Greek psiloi (slinger) is too OP

https://github.com/ZetaGlest/zetaglest-data/blob/develop/techs/zetapack/factions/greece/units/psiloi/psiloi.xml

**Comment by andy5995** [comment]
@KeithSammut said they move too fast.

I'm not sure yet if they're OP. The max unit count is 10. I suspect if Rome attacked early, the spearmen would wipe out the slingers w/o any problem.

**Comment by KeithSammut** [comment]
oh alright I didn't know that, should've made enough research

**Comment by andy5995** [comment]
>should've made enough research

Don't worry :) It was good that you mentioned it and worth a discussion. I'll leave the ticket open. Maybe @Jammyjamjamman has some feedback, too. He has played Greece a few times.
