### ISSUE TITLE
write a tutorial for the Persian faction

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#63]
There currently is no tutorial for the Persian faction.

For examples, you can view the existing tutorials (xml files) in

https://github.com/ZetaGlest/zetaglest-data/tree/develop/tutorials

An ZetaGlest LUA scripting reference is at

https://zetaglest.github.io/docs/lua_scripting.html

The functions are categorized by links in the left-hand panel.

**Comment by KeithSammut** [comment]
alright

**Comment by andy5995** [comment]
This was done by @KeithSammut in https://github.com/ZetaGlest/zetaglest-data/commit/8d03297fa53d6a75dc0450b6e74f9ff4a777306b Thanks Keith!

**Comment by KeithSammut** [comment]
Welcome :)
