### ISSUE TITLE
replace some icons

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#8]
As this fork is called "ZetaGlest", it could use some new icons.

@nedrichards from [Endless](https://endlessos.com/home/), any interest in doing a PR for this project?

**Comment by nedrichards** [comment]
Not currently I'm afraid - the MegaGlest icon we created was just 'sitting around' and I thought it'd do more good upstream. If that changes I'll let you know!

**Comment by andy5995** [comment]
Ah, well, I appreciate the reply. Thank you!

**Comment by andy5995** [comment]
We'll try to add more specific information here. Anyone who thinks he or she might be interested, please hit the "subscribe" button to stay updated.

**Comment by andy5995** [comment]
@ckbrewer15 

Any interest in redesigning these icons? They should all be the same design, just different formats (you'll see 3 in that directory). The specs for each file should match the existing.

https://github.com/ZetaGlest/zetaglest-data/tree/develop/others/icons

**Comment by andy5995** [comment]
Created a new ticket with some specifics and updated info https://github.com/ZetaGlest/zetaglest-source/issues/250
