### ISSUE TITLE
new banner/in-game image is needed

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#9]
ZetaGlest needs a new logo

**Comment by andy5995** [comment]
So.. At a minimum, the Mega should be changed to Zeta.. but a complete redesign would be the best! :)

![logo](https://user-images.githubusercontent.com/16764864/35014673-216fbb3e-fad7-11e7-88e9-66b9535fdfa2.png)

**Comment by sexybiggetje** [comment]
![zetaglest](https://user-images.githubusercontent.com/60222/35067529-7ef00f0e-fbd4-11e7-9dc2-a2191f0dc6af.png)

How about this little piece of placeholder art.

**Comment by ckbrewer15** [comment]
Hello, I came across your help wanted and thought I would give it a go. I don't really know the style of the game, so maybe it doesn't fit for this.

The font is "Skia". The shield I got from IconFinder, it has a Creative Commons license, please find it here: https://www.iconfinder.com/icons/299070/shield_icon#size=512

I have the PSD if you want it, I was unable to upload it here as file type was not supported. Have a great day.
 
![logo](https://user-images.githubusercontent.com/5055017/35285831-5b0c0082-002c-11e8-860a-b473d6daab2d.png)

**Comment by andy5995** [comment]
@ckbrewer15 That's a very cool graphic! Thank you, but it doesn't quite fit the game.

Here are a few screenshots:

https://github.com/ZetaGlest/screenshots

Also, there are some vidoeo on YouTube of MegaGlest, from which ZetaGlest is forked:

https://www.youtube.com/watch?v=glWKT8hDmjw

@sexybiggetje , I'm sorry I missed your message. I believe we'll be able to use that placeholder until some new graphics are designed. Thank you :)

**Comment by andy5995** [comment]
@ckbrewer15 You're welcome to join our discord server if you'd like to run any more ideas by our team. https://discord.gg/WaAaXS7

**Comment by IsshMG** [comment]
I will try a short at this once I finalize the chat ping sound.

**Comment by andy5995** [comment]
The specs are

* uncompressed tga
* transparent background
* 512x256

The specs may be more flexible, but until we understand more how things work, let's go with that. That's for the logo used at intro and main menu, and can be also used externally, on the web site, etc.

**Comment by ckbrewer15** [comment]
Sorry for delay responding, thank you for invite. Please let me know if you need any help with anything. Have a good one!

**Comment by andy5995** [comment]
@ckbrewer15 , no problem about the delay. I prefer to wait for people to respond, but after some experience maintaining projects, I've learned that more often than not, I don't hear back. Would love to have you help on some other stuff. This project uses a lot of graphics, and I expect to be creating more tickets soon. May want to hit "Watch" on the repo. Also, there is a ticket for replacing some icons. I'll update that and ping you. Thanks for the offer!

You're also welcome to join our [Discord server](https://discord.gg/WaAaXS7), and keep up to date, and offer suggestions if you think of any.

**Comment by andy5995** [comment]
@IsshMG What's the status of the chat sound and logo?

**Comment by andy5995** [comment]
@jamJamDev any interest in designing a new logo, based on the specs mentioned above?

**Comment by andy5995** [comment]
On Discord, @Jammyjamjamman asked:

>If you had to think of a single thing/ object/ feeling/ cheese that described ZG, what would it be?

**Comment by jamJamDev** [comment]
@andy5995 hey, sorry I didn't seem to notice the email with my mention & didn't see an email til your last comment. Do you guys have a logo?
Sorry I've been kind of off the grid - had a lot going on finding & starting a new job, moving, & more.

**Comment by mathusummut** [comment]
We don't have a proper logo yet, and would appreciate any help designing one. :)

**Comment by jamJamDev** [comment]
Cool! if I get some time, I'll definitely see what I might be able to come up with :)

**Comment by andy5995** [comment]
@jamJamDev , no worries, I remember last time we chatted that you were busy job-hunting, and I know some GitHub emails slip by. :)

In the future, is it ok if I email you directly if I'm looking for help with something?

@Jammyjamjamman offered to work on the logo, but if you both wind up submitting some ideas, that shouldn't conflict too much (time permitting, of course ;)).

You're welcome to join our [Discord channel](https://discord.gg/WaAaXS7) and keep in touch when it's convenient for you.

Nice to hear from you again, Jamie.

**Comment by jamJamDev** [comment]
Yeah that'd be fine :) I can't guarantee I'll always be able to help since I have some personal projects I'm trying to get off the ground, but I'd love to help out a little here & there when I can!

**Comment by andy5995** [comment]
I haven't heard any complaints about our existing log. We can always think about redesigning later. Updating icons are the priority right now.

**Comment by andy5995** [comment]
@mathusummut just told me on Discord that we need a new ZG Logo. Reopening.

**Comment by andy5995** [comment]
ticket for 512x512 image opened at https://github.com/ZetaGlest/zetaglest-data/issues/224
