### ISSUE TITLE
make an alternate MagiTech NetworkGameSetup

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-data#97]
To help with #48 

We should have a 3rd mgg file in the same directory this is in:

https://github.com/ZetaGlest/zetaglest-data/blob/develop/data/defaultNetworkGameSetup.mgg

The file could be called defaultMagitechNetworkGameSetup.mgg

Anyone wishing to run a headless server could specify that magitech mgg file as the default (cc @biels ;) )

**Comment by andy5995** [comment]
Seems there's no demand for this atm. Closing...

**Comment by biels** [comment]
Don't know why, but I missed the first notification. Surely there is demand for this, you can reopen! And given the extremely low implementation cost I would add it right away.

**Comment by andy5995** [comment]
Thanks @biels . Would be good to add a README to that folder with some short text on how to use it.
